export const jobs = [
	{
		jobTitle: "Software Engineer",
		companyName: "Prelim",
		jobUrl:
			"https://jobs.ashbyhq.com/prelim/62449307-e366-4c92-8d22-9a9f8ec11afa",
		appliedDate: "2025-09-02",
		status: "Applied",
		statusDate: "2025-09-02",
		archived: "No",
		salary: "$185K - $200K",
		location: "Remote",
		contactName: "Darren Lu",
		contactEmail: "darren@prelim.com",
		nextFollowUpDate: "2025-09-08",
		lastContactedDate: "2025-09-02",
		companyInfo: {
			industry: "Financial",
			size: "51-200 employees",
			website: "https://prelim.com/",
			linkedin: "https://www.linkedin.com/company/prelimsolutions/",
		},
		jobDescription:
			"Design and implement onboarding flows for every financial service imaginable, deposits, loans, treasury services, credit cards, business accounts, and emerging financial products.",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: null,
	},
	{
		jobTitle: "Full Stack Engineer",
		companyName: "Gravity",
		jobUrl:
			"https://jobs.ashbyhq.com/GravityClimate/68676a7a-38a5-4206-ae5c-ef3f9530211d/application?utm_source=Simplify",
		appliedDate: "2025-09-02",
		status: "Applied",
		statusDate: "2025-09-02",
		archived: "No",
		salary: "$185K - $200K",
		location: "Remote",
		contactName: "Jane Smith",
		contactEmail: "",
		nextFollowUpDate: "2025-09-16",
		lastContactedDate: "2025-09-02",
		companyInfo: {
			industry: "Climate Tech",
			size: "51-200 employees",
			website: "https://www.gravityclimate.com",
			linkedin: "https://www.linkedin.com/company/gravityclimate/",
		},
		jobDescription: "Work on cutting-edge climate solutions.",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: null,
	},

	{
		jobTitle: "Web Developer",
		companyName: "GRUVER",
		jobUrl: "https://gruve.ai/careers/?gh_jid=4856854008",
		appliedDate: "2025-08-13",
		status: "Applied",
		statusDate: "2025-08-13",
		archived: "No",
		salary: "$65,000 - $90,000",
		location: "Remote",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "AI",
			size: "",
			website: "https://gruve.ai/",
			linkedin: "",
		},
		jobDescription: "",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
	{
		jobTitle: "Frontend Software Engineer",
		companyName: "O’Reilly Media",
		jobUrl: "https://jobs.jobvite.com/oreilly-media/job/oP7Qwfw2/",
		appliedDate: "2025-08-13",
		status: "Applied",
		statusDate: "2025-08-13",
		archived: "No",
		salary: "$98,000 - $144,000",
		location: "Remote",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "",
			size: "",
			website: "https://www.oreilly.com/",
			linkedin: "",
		},
		jobDescription: "",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
	{
		jobTitle: "Frontend React Developer",
		companyName: "Tagada\nPay",
		jobUrl: "https://www.tagada.io/careers/frontend-react-developer",
		appliedDate: "2025-08-21",
		status: "Applied",
		statusDate: "2025-08-21",
		archived: "No",
		salary: "$80k - $120k + Equity",
		location: "Remote",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "",
			size: "",
			website: "https://www.tagada.io/",
			linkedin: "",
		},
		jobDescription: "",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
	{
		jobTitle: "Early Career Software Engineer",
		companyName: "Citizen Health",
		jobUrl:
			"https://jobs.ashbyhq.com/Citizen%20Health/ea388b8a-16cb-4b1b-b64f-479f0dc69764?source=7rN0da4Arn",
		appliedDate: "2025-08-26",
		status: "Applied",
		statusDate: "2025-08-26",
		archived: "No",
		salary: "$130K – $180K",
		location: "Hybrid",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "",
			size: "",
			website: "",
			linkedin: "",
		},
		jobDescription: "",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
	{
		jobTitle: " Full-Stack Engineer",
		companyName: "Denu Recruit ",
		jobUrl:
			"https://www.linkedin.com/jobs/search/?currentJobId=4288893862&distance=25&f_E=2&f_TPR=r86400&geoId=103644278&keywords=Web%20Developer&origin=JOB_SEARCH_PAGE_JOB_FILTER&refresh=true",
		appliedDate: "2025-08-26",
		status: "Applied",
		statusDate: "2025-08-26",
		archived: "No",
		salary: "$120,000 - $150,000",
		location: "Remote",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "",
			size: "",
			website: "",
			linkedin: "",
		},
		jobDescription: "",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
	{
		jobTitle: "Associate Software Engineer",
		companyName: "Independence Pet Group",
		jobUrl:
			"https://independencepetgroup.wd12.myworkdayjobs.com/en-US/Careers/job/Associate-Software-Engineer_JR101144",
		appliedDate: "2025-08-26",
		status: "Applied",
		statusDate: "2025-08-26",
		archived: "No",
		salary: "N/A",
		location: "Remote",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "Pet Care",
			size: "",
			website: "https://www.independencepetholdings.com/",
			linkedin: "",
		},
		jobDescription: "",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
	{
		jobTitle: "Frontend Developer",
		companyName: "Majorly",
		jobUrl:
			"https://www.linkedin.com/jobs/search/?currentJobId=4291304990&f_C=104460788&geoId=92000000&origin=COMPANY_PAGE_JOBS_CLUSTER_EXPANSION&originToLandingJobPostings=4291304990&trk=d_flagship3_company_posts",
		appliedDate: "2025-08-26",
		status: "Applied",
		statusDate: "2025-08-26",
		archived: "No",
		salary: "$30/hr",
		location: "Remote",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "Education",
			size: "11-50",
			website: "https://www.getmajorly.com/",
			linkedin: "https://www.linkedin.com/company/majorlyeducation/",
		},
		jobDescription: "",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
	{
		jobTitle: "Full-Stack Software Engineer",
		companyName: "Securly",
		jobUrl: "https://www.securly.com/job-description?gh_jid=6855714",
		appliedDate: "2025-08-26",
		status: "Applied",
		statusDate: "2025-08-26",
		archived: "No",
		salary: "N/A",
		location: "Remote",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "Wellness",
			size: "",
			website: "https://www.securly.com/",
			linkedin: "",
		},
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
	{
		jobTitle: "Software Engineer",
		companyName: "Operant",
		jobUrl: "https://job-boards.greenhouse.io/operantai/jobs/4895551008",
		appliedDate: "2025-08-26",
		status: "Applied",
		statusDate: "2025-08-26",
		archived: "No",
		salary: "N/A",
		location: "Remote",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "AI",
			size: "",
			website: "https://operant.ai",
			linkedin: "",
		},
		jobDescription: "",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
	{
		jobTitle: "Part-Time Full Stack Engineer",
		companyName: "NextGen Healthcare",
		jobUrl:
			"https://www.linkedin.com/jobs/search/?currentJobId=4289684972&f_C=101064613&geoId=92000000&origin=COMPANY_PAGE_JOBS_CLUSTER_EXPANSION&originToLandingJobPostings=4289684972%2C4288825016%2C4289697052%2C4291232907&trk=d_flagship3_company",
		appliedDate: "2025-09-02",
		status: "Applied",
		statusDate: "2025-09-02",
		archived: "No",
		salary: "$25/hr",
		location: "Remote",
		contactName: "",
		contactEmail: "",
		nextFollowUpDate: null,
		lastContactedDate: null,
		companyInfo: {
			industry: "",
			size: "11-50",
			website: "https://www.nextgencodingcompany.com/",
			linkedin: "",
		},
		jobDescription: "",
		interviewNotes: null,
		interviewDate: null,
		offerDetails: null,
		rejectionReason: null,
		dateArchived: null,
		notes: "Imported from Huntr",
	},
];
